name: private-ci
run-name: ${{ github.actor }} is running private CI
on:
  workflow_dispatch:

env:
  PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
  MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
  MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
  MAIL_TO: ${{ secrets.MAIL_TO }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v7
        with:
          python-version: "3.13"

      - run: |
          sudo apt-get update
          sudo apt-get install -y \
            texlive-latex-base \
            texlive-latex-extra \
            texlive-fonts-recommended

      - name: cv-en
        run: |
          python -c "
          import os
          env = os.environ
          PHONE_NUMBER = env.get('PHONE_NUMBER')
          file = open('en-cv.tex', 'r')
          content = file.read()
          content = content.replace('PHONE-PLACEHOLDER', PHONE_NUMBER)
          with open('processed-en-cv.tex', 'w') as f:
            f.write(content)
          file.close()
          "

      - name: cv-tr
        run: |
          python -c "
          import os
          env = os.environ
          PHONE_NUMBER = env.get('PHONE_NUMBER')
          file = open('tr-cv.tex', 'r')
          content = file.read()
          content = content.replace('PHONE-PLACEHOLDER', PHONE_NUMBER)
          with open('processed-tr-cv.tex', 'w') as f:
            f.write(content)
          file.close()
          "

      - name: Compile PDFs
        run: |
          mkdir -p dist
          pdflatex -interaction=nonstopmode -output-directory=./dist processed-en-cv.tex
          pdflatex -interaction=nonstopmode -output-directory=./dist processed-tr-cv.tex

      - name: Send CV by email
        uses: dawidd6/action-send-mail@v18
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ env.MAIL_USERNAME }}
          password: ${{ env.MAIL_PASSWORD }}
          subject: "CV Build - ${{ github.sha }}"
          to: ${{ env.MAIL_TO }}
          from: ${{ env.MAIL_USERNAME }}
          body: |
            CV successfully compiled.

            Repository: ${{ github.repository }}
            Commit: ${{ github.sha }}
          attachments: dist/processed-*.pdf
